accounts/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signup_success/", views.SignUpSuccessView.as_view(), name="signup_success"),
    path(
        "login/", auth_views.LoginView.as_view(template_name="login.html"), name="login"
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="logout.html"),
        name="logout",
    ),
]

photo/urls.py
from django.urls import path
from . import views

app_name = "photo"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("post/", views.CreatePhotoView.as_view(), name="post"),
    path("post_done/", views.PostSuccessView.as_view(), name="post_done"),
    path("photos/<int:category>", views.CategoryView.as_view(), name="photos_category"),
    path("user-list/<int:user>", views.UserView.as_view(), name="user_list"),
    path("photo-detail/<int:pk>", views.DetailView.as_view(), name="photo_detail"),
    path("mypage/", views.MypageView.as_view(), name="mypage"),
    path(
        "photo/<int:pk>/delete/", views.PhotoDeleteView.as_view(), name="photo_delete"
    ),
]

photoproject/urls.py
from django.contrib import admin
from django.urls import path, include


from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("photo.urls")),
    path("", include("accounts.urls")),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(template_name="password_reset.html"),
        name="password_reset",
    ),
    path(
        "password_reset/done",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset/<uid64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset.form.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset_done.html"
        ),
        name="password_reset_complate",
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

photo/models.py
from django.db import models

# Create your models here.
from accounts.models import CustomUser


class Category(models.Model):
    title = models.CharField(verbose_name="カテゴリー", max_length=20)

    def __str__(self):
        return self.title


class PhotoPost(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name="ユーザ", on_delete=models.CASCADE)
    category = models.ForeignKey(
        Category, verbose_name="カテゴリ", on_delete=models.PROTECT
    )
    title = models.CharField(verbose_name="タイトル", max_length=200)
    comment = models.TextField(verbose_name="コメント")
    image1 = models.ImageField(verbose_name="イメージ1", upload_to="photos", blank=True)
    posted_at = models.DateTimeField(verbose_name="投稿日時", auto_now=True)

    def __str__(self):
        return self.title

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email", "password1", "password2")

photo/forms.py
from django.forms import ModelForm
from .models import PhotoPost


class PhotoPostForm(ModelForm):
    class Meta:
        model = PhotoPost
        fields = ["category", "title", "comment", "image1"]

accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import CreateView, TemplateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = "signup.html"
    success_url = reverse_lazy("accounts:signup_success")

    def form_valid(self, form):
        user = form.save()
        self.object = user
        return super().form_valid(form)


class SignUpSuccessView(TemplateView):
    template_name = "signup_success.html"

photo/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView, ListView

from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import PhotoPostForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from .models import PhotoPost

from django.views.generic import DetailView

from django.views.generic import DeleteView


class IndexView(ListView):
    template_name = "index.html"
    queryset = PhotoPost.objects.order_by("-posted_at")
    paginate_by = 6


@method_decorator(login_required, name="dispatch")
class CreatePhotoView(CreateView):
    form_class = PhotoPostForm
    template_name = "post_photo.html"
    success_url = reverse_lazy("photo:post_done")

    def form_valid(self, form):
        postdata = form.save(commit=False)
        postdata.user = self.request.user
        postdata.save()
        return super().form_valid(form)


class PostSuccessView(TemplateView):
    template_name = "post_success.html"


class CategoryView(ListView):
    template_name = "index.html"
    paginate_by = 9

    def get_queryset(self):
        category_id = self.kwargs["category"]
        categories = PhotoPost.objects.filter(category=category_id).order_by(
            "-posted_at"
        )
        return categories


class UserView(ListView):
    template_name = "index.html"
    paginate_by = 9

    def get_queryset(self):
        user_id = self.kwargs["user"]
        user_list = PhotoPost.objects.filter(user=user_id).order_by("-posted_at")
        return user_list


class DetailView(DetailView):
    template_name = "detail.html"
    model = PhotoPost


class MypageView(ListView):
    template_name = "mypage.html"
    paginate_by = 9

    def get_queryset(self):
        queryset = PhotoPost.objects.filter(user=self.request.user).order_by(
            "-posted_at"
        )
        return queryset


class PhotoDeleteView(DeleteView):
    model = PhotoPost
    template_name = "photo_delete.html"
    success_url = reverse_lazy("photo:mypage")

    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)

accounts/templates/login.html
{% load static %}
<!doctype html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.84.0">
  <title>login</title>





  <!-- Bootstrap core CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>


  <!-- Custom styles for this template -->
  <link href="{% static 'css/signin.css' %}" rel="stylesheet">
</head>

<body class="text-center">

  <main class="form-signin">
    {% if form.errors %}
    <p style="color:red">ユーザ名とパスワードが一致しません</p>
    {% endif %}
    <form method="post">
      {% csrf_token %}
      <br>
      <h1 class="h3 mb-3 fw-normal">log in page</h1>
      <br>
      <br>
      <label for="Username" class="visually-hidden">User name</label>

      <input type="text" name="username" id="id_username" maxlength="150" autocapitalize="none" autocomplete="username"
        class="form-control" placeholder="ユーザ名" required autofocus>
      <label for="password" class="visually-hidden">password</label>

      <input type="password" name="password" id="id_password" autocomplete="current-password" class="form-control"
        placeholder="パスワード" required autofocus>
      <input class="w-100 btn btn-lg btn-primary" type="submit" value="ログイン">

      <br><br>


      <input type="hidden" name="next" value="{% url 'photo:index' %}">
    </form>
  </main>
</body>

</html>

accounts/templates/logout.html
{% extends 'base.html' %}
{% block title %}log out{% endblock %}

{% block contents %}

<div class="container">

    <div class="row">

        <div class="col offset-4 py-4">
            <h3>ログアウトしました</h3>
            <p><a herf="{% url 'photo:index' %}">top page</a></p>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/password_reset.html
{% extends 'base.html' %}
{% block title %}pass word reset{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="col py-4">
            <hr>
            <h3>パスワードをリセットする？</h3>
            <p>登録済みのメールアドレスを入力してください
                パスワードをリセットのリンクを記載したメールをお送りします
            </p>
            <br>
            <form action="" method="POST" class="text-center">
                {% csrf_token %}
                {{form}}
                <input type="submit" value="メールを受け取る"><br>
            </form>
            <br>
            <a href="{% url 'photo:index' %}">Strategy Information</a>
            <hr>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/password_reset_done.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <style>
        .pad {
            background-color: lavender;
            border: solid 2px;
            padding-top: 30px;
            padding-bottom: 50px;
            padding-left: 100px;
            margin-top: 50px;
            margin-right: 70px;
            margin-left: 70px;
        }
    </style>
</head>

<body>
    <div class="pad">
        <h2>パスワードがリセットされました</h2>
        <a href="{% url 'photo:index' %}">phto gallery</a>
    </div>
</body>

</html>

accounts/templates/password_reset_sent.html
{% extends 'base.html' %}
{% block title %}send pass word reset{% endblock %}

{% block contents %}

<hr>
<div class="container">
    <div class="row">

        <div class="col offset-2 py-4">
            <h5>パスワードのリセット手順を送信しました</h5>
            <br>
            <h6>メールが届かない場合は登録されているメールアドレスかを確認してください。また、迷惑メールフォルダも確認してみてください</h6>
            <br>
            <a href="{% url 'photo:index' %}">photogalley</a>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}
{% block title %}signup{% endblock %}

{% block contents %}
<hr>
<div class="container">

    <div class="row">
        <div class="col offset-2">
            <h3>sainappu</h3>
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                <p>
                    {{ field.label_tag }}<br>
                    {{ field }}
                    {% if field.help_text %}
                    <small style="color:grey">{{field.help_text}}</small>
                    {% endif %}
                    {% for error in field.errors %}
                <p style="color:red">{{ error }}</p>
                {% endfor %}
                </p>
                {% endfor %}
                <p style="color:red">
                    *メアドはパスワードリセットに必要なので登録してください
                </p>
                <input type="submit" value="sign up">
            </form>
            <br>
            <p><a href="{% url 'photo:index' %}">登録をやめる</a></p>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/signup_success.html
{% extends 'base.html' %}
{% block title %}registation complate{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="col offset-4 py-4">
            <h3>登録完了</h3>
            <p><a href="{% url 'accounts:login' %}">ログインはこちら</a></p>
        </div>
    </div>
</div>
{% endblock %}

photo/templates/base.html
{% load static %}

<!doctype html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.84.0">
  <title>{% block title %}{% endblock %}</title>



  <!-- Bootstrap core CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <style>
    .bd-placeholder-img {
      font-size: 1.5rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>


</head>

<body>

  <header>
    <div class="collapse bg-dark" id="navbarHeader">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 col-md-7 py-4">
            <h4 class="text-white">自分にピッタリな情報を見つけよう！</h4>
            <p class="text-muted">ユーザー登録をすれば、誰でも参加できる攻略情報投稿サイトです。うその情報や悪口、誹謗中傷は投稿しないでください。消します。
            </p>
          </div>
          <div class="col-sm-4 offset-md-1 py-4">
            <h4 class="text-white">Contact</h4>
            <ul class="list-unstyled">
              {% if user.is_authenticated %}
              <li><a href="{% url 'photo:mypage' %}" class="text-white">マイページ</a></li>
              <li><a href="{% url 'accounts:logout' %}" class="text-white">ログアウト</a></li>
              <li><a href="{% url 'password_reset' %}" class="text-white">パスワードリセット</a></li>
              {% else %}
              <li><a href="{% url 'accounts:signup' %}" class="text-white">サインアップ</a></li>
              <li><a href="{% url 'accounts:login' %}" class="text-white">ログイン</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
      <div class="container">
        <a href="{% url 'photo:index' %}" class="navbar-brand d-flex align-items-center">

          <strong>Strategy Information</strong>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
          aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </div>
  </header>

  <main>
    {% block contents %}{% endblock %}

  </main>

  <footer class="text-muted py-5">
    <div class="container">
      <p class="float-end mb-1">
      </p>
      <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>

    </div>
  </footer>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>


</body>

</html>

photo/templates/detail.html
{% extends 'base.html' %}

{% block title%}photo detail{% endblock %}

{% block contents %}
<br>
<div class="container">
    <div class="row">
        <div class="col offset-3">

            <h2>{{object.title}}</h2>
            <p>{{object.comment}}</p>
            <br>
            <p>{{object.posted_at}}に投稿</p>
            {% if object.image1 %}
            <p><img src="{{object.image1.url}}"></img></p>
            {% endif %}
            {% if request.user == object.user%}
            <form method="POST">
                <a href="{% url 'photo:photo_delete' object.pk %}" class="btn btn-primary my-2">削除する</a>
            </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

photo/templates/index.html
{% extends 'base.html' %}

{% block title%}kouryaku{% endblock %}

{% block contents %}
{% include "photos_title.html" %}
{% include "photos_list.html" %}
{% include "pagination.html" %}

{% endblock %}

photo/templates/mypage.html
{% extends 'base.html' %}

{% block title%}mypage{% endblock %}

{% block contents %}

{% if user.is_authenticated %}
<br>
<div style="text-align: center;">
  <h4>{{user.username}}のマイページ</h4>
  {% if object_list.count == 0 %}
  <p>{{user.username}}の投稿はありません</p>
  {% else %}
  <p>投稿<strong>{{object_list.count}}</strong>件</p>
  {% endif %}
  <a href="{% url 'photo:post' %}">投稿する</a>

</div>
<hr>
{% endif %}
{% include "photos_list.html" %}
{% include "pagination.html" %}

{% endblock %}

photo/templates/pagination.html
<ul class="pagination" style="justify-content:center">
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}
    {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
    <li class="page-item active">
        <span class="page-link">{{ num }}</span>
    </li>
    {% else %}
    <li class="page-item">
        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    {% endif %}
</ul>

photo/templates/photo_delete.html
{% extends 'base.html' %}

{% block title%}photo delete{% endblock %}

{% block contents %}
<br>
<div class="container">
    <div class="row">
        <div class="col offset-3">
            <form method="POST">
                <br>
                <p>削除するぞ？</p>
                {% csrf_token %}
                <button class="btn btn-primary my-2" type="submit">削除</button>
                <a href="{% url 'photo:photo_detail'  object.pk %}" class="btn btn-secondary my-2">キャンセル</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

photo/templates/photos_list.html
<div class="album py-5 bg-light">
  <div class="container">

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for record in object_list %}
      <div class="col">
        <div class="card shadow-sm">


          <div class="card-body">
            <p class="card-text">{{record.title}}</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary"
                  onclick="location.href='{% url 'photo:photo_detail' record.pk %}'">みる</button>
                <button type="button" class="btn btn-sm btn-outline-secondary"
                  onclick="location.href='{% url 'photo:photos_category' category=record.category.id %}'">{{record.category.title}}</button>
              </div>
              <a href="{% url 'photo:user_list' user=record.user.id %}"><small
                  class="text-muted">{{record.user.username}}</small></a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

photo/templates/photos_title.html
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">Strategy Information Site</h1>
      <h2 class="fw-light">・・・攻略情報サイト・・・</h2>
      <p class="lead text-muted">ココはゲーム攻略情報投稿サイトです。ゲームのことの攻略情報を投稿して、共有しよう。間違った情報は投稿しないでな</p>
      <p>
        {% if user.is_authenticated %}
        <a href="{% url 'photo:post' %}" class="btn btn-primary my-2">攻略情報を投稿する</a>
        <a href="{% url 'accounts:logout' %}" class="btn btn-secondary">ログアウト</a>
        {% else %}
        <a href="{% url 'accounts:signup' %}" class="btn btn-primary my-2">サインアップ</a>
        <a href="{% url 'accounts:login' %}" class="btn btn-secondary my-2">ログイン</a>
        {% endif %}
      </p>
    </div>
  </div>
</section>

photo/templates/post_photo.html
{% extends 'base.html' %}
{% block title %}post{% endblock %}

{% block contents %}

<br>
<div class="container">

    <div class="row">
        <div class="col offset-2">

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    <tr>
                        <th>カテゴリ</th>
                        <td>{{form.category}}</td>
                    </tr>
                    <tr>
                        <th>タイトル</th>
                        <td>{{form.title}}</td>
                    </tr>

                    <tr>
                        <th>コメント</th>
                        <td>{{form.comment}}</td>
                    </tr>
                    <tr>
                        <th>画像</th>
                        <td>{{form.image1}}</td>
                    </tr>
                </table>
                <hr>
                <button type="submit">投稿する</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

photo/templates/post_success.html
{% extends 'base.html' %}
{% block title %}post{% endblock %}

{% block contents %}

<br><br>
<div class="container">
    <div class="row">
        <div class="col offset-2">
            <h4>投稿が完了しました</h4>
        </div>
    </div>
</div>
{% endblock %}